  
  const initCt = {
  colors: {},
  textSizes: {},
  apiData: {},
  toggles: {},
  colors2: {},
  textSizes2: {},
  toggles2: {},
  apiData2: {},
  true: 'true',
  content: {},
  userData: {},
  formsData: {},
  dev: {},
  endpoint: '',
  listsData: {},
  infinite: false,
  teste: '...',
  mocks: {},
  all: {},
  autocomp: {},
  mergedObj: {},
  sc: {},
};